
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-courses-s26-01
owner: ucsb-cs156-s26
repo_name: proj-courses-s26-01
pull_requests: [{"author":{"id":"U_kgDOCv5aZg","is_bot":false,"login":"oscarv06-cs","name":""},"headRefName":"feature/Implement-GeneralEducationSearchPage","number":45,"title":"Implemented GE Search Feature","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-01/pull/45"},{"author":{"id":"U_kgDOB3Dg5Q","is_bot":false,"login":"Yinwu-Jinliu","name":"Binghao Cui"},"headRefName":"Binghao_Vitest_teardown_bugfix","number":30,"title":"Fix frontend coverage teardown errors","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-01/pull/30"},{"author":{"id":"U_kgDOB3Dg5Q","is_bot":false,"login":"Yinwu-Jinliu","name":"Binghao Cui"},"headRefName":"Binghao_pagination-frontend","number":27,"title":"Add frontend pagination to admin users page","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-01/pull/27"},{"author":{"id":"U_kgDOB2kI4w","is_bot":false,"login":"Junyixi","name":"schen"},"headRefName":"sq-error-page-clean","number":22,"title":"Shanqin - Create user friendly custom error page","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-01/pull/22"}]
