
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-courses-s26-01
owner: ucsb-cs156-s26
repo_name: proj-courses-s26-01
pull_requests: [{"author":{"id":"U_kgDOB2kI4w","is_bot":false,"login":"Junyixi","name":"schen"},"headRefName":"sq-error-page-clean","number":22,"title":"Shanqin - Create user friendly custom error page","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-01/pull/22"},{"author":{"id":"MDQ6VXNlcjMzOTE0MTc1","is_bot":false,"login":"surew1n","name":"Sherwin Riahi"},"headRefName":"Sherwin-Improve-integration-test-start-time","number":21,"title":"Sherwin - edit pom.xml to improve integration test start time","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-01/pull/21"},{"author":{"id":"U_kgDOCeYN-A","is_bot":false,"login":"Protocol-X3","name":"Whisper"},"headRefName":"wp-search-fb","number":19,"title":"wp - Add proper message for CourseHistory/Location/Instructor search and test","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-01/pull/19"}]
